name: coverage

on:
  push:
    paths:
      - "**/*.rs"
      - "**/Cargo.toml"
      - "**/Cargo.lock"
      - ".github/workflows/rust-ci.yml"

env:
  RUST_BACKTRACE: 1

jobs:
  coverage:
    runs-on: ubuntu-latest
    if: ${{ github.actor != 'dependabot[bot]' }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable

      - name: Install cargo binstall
        uses: cargo-bins/cargo-binstall@main

      - name: Install tarpaulin
        run: cargo binstall --no-confirm cargo-tarpaulin

      - name: Setup Cache
        uses: Swatinem/rust-cache@v2

      - name: Report test coverage
        run: |
          cargo tarpaulin \
            --engine llvm \
            --follow-exec \
            --post-test-delay 10 \
            --exclude-files src/{args,client}.rs \
            --coveralls ${{ secrets.COVERALLS_REPO_TOKEN }}
